language: perl
perl:
  - "5.16"

cache:
  directories:
    - $HOME/core-develop/.cache/pip

addons:
  apt:
    packages:
      - python-virtualenv

sudo: false

# cache:
#  directories:
#    - $HOME/.cache/pip

before_install:
  - cd ..
  - git clone -b perlclient https://github.com/kkellerlbl/data_api.git core-develop
  - ( cd core-develop && git submodule init && git submodule update )
# need the core for starting services
  - cd core-develop
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - python setup.py install -vv
#  - redis-server redis.conf &

install:
# build the codecov module
  - cd ../data_api_perl_clients
  - cpanm  --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - perl Build.PL
  - ./Build installdeps --cpan-client 'cpanm'
  - ./Build install --cpan-client 'cpanm'

before_script:
#  - source ../core-develop/venv/bin/activate
#  - data_api_start_service.py --service taxon --config ../core-develop/deployment.cfg > taxonAPI.out 2> taxonAPI.err &
#  - data_api_start_service.py --service assembly --config ../core-develop/deployment.cfg > assemblyAPI.out 2> assemblyAPI.err &
  - data_api_start_service.py --service assembly --config ../core-develop/deployment.cfg &
  - pwd
  - ls -l ..
  - ps axuwww
  - sleep 5
#  - cat assemblyAPI.out
##  - data_api_start_service.py --service genomeannotation --config deployment.cfg > genomeannotationAPI.out &

script:
  - curl http://localhost:9102
  - printf "PERL5LIB = $PERL5LIB \n"
# see if python clients work
  - assembly_client_driver.py
# dummy edit
  - ./Build testcover
#  - coverage run `which nosetests` -c nose.cfg -c nose-local.cfg
#  - coverage report --skip-covered

env:
#  - KB_DEPLOY_URL="dir_cache"
  - KB_DEPLOY_URL="dir_nocache"
#  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-ci.cfg
#  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-ci.cfg

after_success:
  - cover -report codecov
  - kill $(cat taxonAPI.pid)
  - kill $(cat assemblyAPI.pid)
#  - kill $(cat genomeannotationAPI.pid)
# Make service logs easy to inspect, then clean up
  - cat taxonAPI.out
  - cat assemblyAPI.out
  - cat gaAPI.out  
  - rm -f taxonAPI.out assemblyAPI.out gaAPI.out
