language: perl
perl:
  - "5.16"

sudo: false

# cache:
#  directories:
#    - $HOME/.cache/pip

before_install:
  - apt-get install python-virtualenv
  - git clone -b develop https://github.com/kbase/data_api.git core-develop
  - ( cd core-develop && git submodule init && git submodule update )
# need the core for starting services
  - cd core-develop
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - python setup.py install -vv
  - cd ..
#  - redis-server redis.conf &

install:
# build the codecov module
  - cpanm  --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - perl Build.PL
  - ./Build installdeps --cpan-client 'cpanm'
  - ./Build install --cpan-client 'cpanm'

before_script:
  - source core-develop/venv/bin/activate
  - nohup data_api_start_service.py --service taxon --config deployment.cfg > taxonAPI.out &
  - nohup data_api_start_service.py --service assembly --config deployment.cfg > assemblyAPI.out &
##  - nohup data_api_start_service.py --service genomeannotation --config deployment.cfg > genomeannotationAPI.out &

script:
  - printf "PERL5LIB = $PERL5LIB \n"
  - find /home/travis/perl5/perlbrew -name ClientAPI.pm
  - ./Build testcover
#  - coverage run `which nosetests` -c nose.cfg -c nose-local.cfg
#  - coverage report --skip-covered

env:
#  - KB_DEPLOY_URL="dir_cache"
  - KB_DEPLOY_URL="dir_nocache"
#  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-ci.cfg
#  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-ci.cfg

after_success:
  - cover -report codecov
#  - kill $(cat taxonAPI.pid)
#  - kill $(cat assemblyAPI.pid)
##  - kill $(cat genomeannotationAPI.pid)
